backend:
  name: git-gateway

local_backend: true

media_folder: content/uploads
public_folder: /static

logo_url: https://lilian.video/static/b618bb4234903b983ce54474b8483482/0580a/lilian-logo-long-holly.png

collections:
  - name: videos
    label: Videos
    folder: content/videos
    preview_path: "v/{{path}}"
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: "Title", widget: "string" }
      - { name: author, label: "Author", widget: "string" }
      - { name: date, label: "Date", widget: datetime }
      - { name: id, label: "Youtube ID", widget: "string" }
      - {
          name: textAuthor,
          label: "Description's author",
          widget: "string",
          required: false,
        }
      - { name: meta, label: "Metadata", widget: "string", required: false }
      - { name: path, label: "Path", widget: "string" }
      - { name: featuredImage, label: "Image", widget: "string" }
      - {
          name: partition,
          label: "Partition",
          widget: "string",
          required: false,
        }
      - { name: body, label: "Body", widget: "markdown", required: false }
